# Generated by Django 4.0.2 on 2022-02-05 20:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=64, unique=True)),
                ("firstname", models.CharField(max_length=64)),
                ("lastname", models.CharField(max_length=64)),
                ("birthday_year", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
